export enum ActionType {
  FetchItems = 'FETCH_ITEMS',
  FetchItemsSuccess = 'FETCH_ITEMS_SUCCESS',
  FetchItemsError = 'FETCH_ITEMS_ERROR',
  SetCourseItemsSearchValue = 'SET_COURSE_ITEMS_SEARCH_VALUE',
  FetchCourse = 'FETCH_COURSE',
  FetchCourseSuccess = 'FETCH_COURSE_SUCCESS',
  FetchCourseError = 'FETCH_COURSE_ERROR',
  AddQuiz = 'ADD_QUIZ',
  DeleteQuiz = 'DELETE_QUIZ',
  UpdateCourseOutline = 'UPDATE_COURSE_OUTLINE',
  SetCourseOutlineSearchValue = 'SET_COURSE_OUTLINE_SEARCH_VALUE',
  OpenDetailsPanel = 'OPEN_DETAILS_PANEL',
  CloseDetailsPanel = 'CLOSE_DETAILS_PANEL',
  ResetCourseEditor = 'RESET_COURSE_EDITOR',
}
