export enum IconType {
  SidebarCourses = 'sidebar-courses',
  SidebarUsers = 'sidebar-users',
  HeaderAvatar = 'header-avatar',
  HelpCircle = 'help-circle',
  FileExport = 'file-export',
  Search = 'search',
  Quiz = 'quiz',
  Delete = 'delete',
  Pencil = 'pencil',
  EventCourse = 'event-course',
  SmartWalkthru = 'smartwalkthru',
  SmartWalkthruSmall = 'smartwalkthru-small',
  Video = 'video',
  VideoSmall = 'video-small',
  Article = 'article',
  ArticleSmall = 'article-small',
  Content = 'content', // TODO: should remove after fixing course item type
  Lesson = 'lesson',
  LessonSmall = 'lesson-small',
  Refresh = 'refresh',
  Plus = 'plus',
  CourseEmpty = 'course-empty',
  LessonEmpty = 'lesson-empty',
  Check = 'check',
}
